name = "ComoniconGUI"
uuid = "04ab0f59-5120-4bbe-b8b6-b34cf3f2b56a"
authors = ["St Z <abczst@outlook.com> and contributors"]
version = "0.1.0"

[deps]
Comonicon = "863f3e99-da2a-4334-8734-de3dacbe5542"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
ExprTools = "e2ba6199-217a-4e67-a87a-7c52f15ade04"
Poptart = "197b51f5-fdb5-5f35-aa9f-0a14f35f5b28"

[compat]
Comonicon = "0.7"
DataStructures = "0.18"
ExprTools = "0.1"
Poptart = "0.3.2"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
